* Vector
** Reverse()
  - Reverse function working fine.
#+begin_src c++
#include "lib_vector.h"
#include "lib_string.h"

int main(){
  abj::Vector<abj::String> x;
  abj::String a("Abhi");
  abj::String b("Jit");
  abj::String c("Paul");
  
  x.push(a);
  x.push(b);
  x.push(c);

  for(int i=0; i<x.size(); i++) x[i].print();
  x.reverse();

  for(int i=0; i<x.size(); i++) x[i].print();
  return 0;
}
#+end_src
* Stemmer
  - A lot of negative index access.
* Steps
  - [X] Made direction public and used it.
  - [X] Whats causing this infinite loop thing? Erase function? NOPE. Its what we push back. WE pushed back the old word (fore*5). As a result, the number of such words will just keep increasing infinitely.
  - [X] Verify the header file. (RUN and check)
  - [X] Load and print the confusion matrices
  - [X] Make a small function inside confusion matrix class where you run med on two words and return the log probablity.
  - [X] Normalize noisy probablity on the size of word
  - [X] Edit MED (add a new Symbol - "<" at the begiing and end ">" of the string to account for insertion, deletion at the start and end.)
  - [X] Edit noisy channel code to account for smaller candidate.
  - [X] test cases for string library
  - [X] test cases for vector library
  - [ ] test cases for stemmer
  - [ ] Combile language model and noisy channel model
  - [ ] Add decision tree in punctuation
  - [ ] Correct decision tree in sentence segmenter
